### ISSUE TITLE
httplib.InvalidURL: nonnumeric port Hatası

### ISSUE THREAD

**Issue by HackerAdana** [HackerAdana/py-admin-finder#3]
```
[Hapf] Target/ Hedef:?> http://google.com

 1 -> Kök dizin
 2 -> Kök dizin + Alt dizin
 3 -> Kök dizin + Alt dizin + Alt alan adları
[Hapf] Level/ Seviye [1-3]:?> 1
 [#] Kontrol ediyoruz: http://google.com/admin.php
Traceback (most recent call last):
  File "./hapf.py", line 278, in <module>
    connection = httplib.HTTPConnection(site)
  File "/usr/lib/python2.7/httplib.py", line 751, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "/usr/lib/python2.7/httplib.py", line 792, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
httplib.InvalidURL: nonnumeric port: '//google.com'
```

**Comment by HackerAdana** [comment]
Gerekli düzenlemeler 2a17f33a ile yapıldı.
